image: node:16

definitions:
  steps:
    - step: &setup-cache
        name: Build and test
        caches:
          - nodeall
          - nodelandingpage
          - nodecms
          - nodeconfig
          - nodeui
          - yarn
  caches:
    nodeall: ./node_modules
    nodelandingpage: ./apps/landing-page/node_modules
    nodecms: ./apps/cms/node_modules
    nodeconfig: ./packages/config/node_modules
    nodeui: ./packages/ui/node_modules
    yarn: /usr/local/share/.cache/yarn

pipelines:
    default:
        - parallel:
          - step:
              <<: *setup-cache
              name: Build
              script:
                  - yarn
                  - yarn build
          - step:
              <<: *setup-cache
              name: Lint
              script:
                  - yarn
                  - yarn lint
          - step:
              <<: *setup-cache
              name: Test
              script:
                  - yarn
                  - yarn test
