version: '3'
services:
  landing-page:
    build:
      dockerfile: ./apps/landing-page/Dockerfile
      args:
        SCOPE: landing-page
      target: dev
    command: [ "yarn", "workspace", "landing-page", "dev" ]
    ports:
      - "3000:3000"
    volumes:
      - ./apps/landing-page/src:/app/apps/landing-page/src
      - ./packages/ui/components:/app/packages/ui/components
      - /app/node_modules/
    restart: on-failure
