version: '3'
services:
  landing-page:
    build:
      dockerfile: ./apps/landing-page/Dockerfile
      args:
        SCOPE: landing-page
      target: dev
    command: [ "yarn", "workspace", "landing-page", "dev" ]
    ports:
      - "3000:3000"
    volumes:
      - ./apps/landing-page/src:/app/apps/landing-page/src
      - ./packages/ui/src:/app/packages/ui/src
      - /app/node_modules/
    restart: on-failure
  cms:
    build:
      dockerfile: ./apps/cms/Dockerfile
      args:
        SCOPE: cms
      target: dev
    command: [ "yarn", "workspace", "cms", "dev" ]
    ports:
      - "1337:1337"
    volumes:
      - ./apps/cms/src:/app/apps/cms/src
      - /app/node_modules/
    restart: on-failure
